
# file paths
rawseqs: "/gpfs/hpchome/taavi74/seqs/raw"
output: "/gpfs/hpchome/taavi74/seqs/output"

# Path to the samples relative to working directory
samples:
  - "I1164_12629_Harvard_SIV_196_06_2_24_12"


