# Path or URL to sample sheet (TSV format, required columns: sample, fq1, fq2, frac)
# sample - unique sample name
# run - sequencing run
# fq1 and fq2 - paths to paired-end fastq file
samples: samples.tsv

# Onsuccess notification email address
email: your@email.addr

# Number of splits for blast
splits: 1
