
# Global parameters -------------------

# path or URL to sample sheet (CSV format, columns: sample, condition, ...)
samples: samples.tsv

# Path to reference genome
ref_genome: "/gpfs/software/VirusSeeker/databases/ref_genomes/human_g1k_v37.fasta"

# Path to RepeatMasker Repbase file (path/to/RMRBSeqs.embl)
repbase_file: "/gpfs/hpchome/taavi74/databases/Repbase/Libraries/RMRBSeqs.embl"

# Raw data directory
datadir: "data"

# Output directory or empty string
outdir: "output"

# Rule parameters ---------------------

# cd-hit
cd-hit:
    threads: 40

# fastq-join
fastq-join:
    maximum_difference: 5
    minimum_overlap: 10

# Fastp
fastp:
    threads: 16

# Filter tantan output
tantan_good:
      min_length: 50
      por_n: 40

# Split fasta
split_fasta:
      batch_size: 2000

# Filter repeatmasker output
repeatmasker_good:
      min_length: 50
      por_n: 40

# MegaBlast against reference genome to remove more host sequences
megablast_ref_genome:
      perc_identity: 85
      evalue: 1e-9
      word_size: 16
      num_descriptions: 1
      num_alignments: 1
