# Path or URL to sample sheet (TSV format, required columns: sample, fq1, fq2, frac)
# sample - unique sample name
# run - sequencing run
# fq1 and fq2 - paths to paired-end fastq file
samples: samples.tsv

email: tapa741@gmail.com

# Split fasta
splits: 2
