$schema: "http://json-schema.org/draft-07/schema#"
description: snakemake configuration file
properties:
  samples:
    type: string
    description: path to samples.tsv file
  email:
    type: string
    description: email address
  splits:
    type: integer
    default: 1
    description: number of files to split fasta file before repeatmasker and blast, defaults to 1

required:
  - samples
  - email
  - splits
